wandb_version: 1

epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.0001
annotator:
  desc: null
  value: 1
augmentation:
  desc: null
  value: true
loss:
  desc: null
  value: CrossEntropyLoss
optimizer:
  desc: null
  value: Adam
scheduler:
  desc: null
  value: ReduceLROnPlateau
place:
  desc: null
  value: laptop
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702917113.421785
    t:
      1:
      - 1
      - 55
      - 79
      2:
      - 1
      - 55
      - 79
      3:
      - 1
      - 16
      - 17
      - 23
      - 37
      4: 3.10.13
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
