wandb_version: 1

epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.0001
annotator:
  desc: null
  value: 2
augmentation:
  desc: null
  value: false
loss:
  desc: null
  value: CrossEntropyLoss
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702731425.528429
    t:
      1:
      - 1
      - 55
      - 79
      2:
      - 1
      - 55
      - 79
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
