wandb_version: 1

model:
  desc: null
  value: smpUNet++
batch_size:
  desc: null
  value: 1
annotator:
  desc: null
  value: 1
place:
  desc: null
  value: lab
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705662455.060132
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 74
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 74
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.11.5
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
