wandb_version: 1

epochs:
  desc: null
  value: 300
batch_size:
  desc: null
  value: 22
lr:
  desc: null
  value: 0.0001
annotator:
  desc: null
  value: 1
model:
  desc: null
  value: smpUNet++
augmentation:
  desc: null
  value: false
loss:
  desc: null
  value: CrossEntropyLoss
optimizer:
  desc: null
  value: Adam
scheduler:
  desc: null
  value: CosineAnnealingLR
place:
  desc: null
  value: lab
mode:
  desc: null
  value: oneclass
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712872952.391938
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 74
      - 79
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 74
      - 79
      3:
      - 1
      - 16
      - 17
      - 23
      - 37
      4: 3.11.7
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
