wandb_version: 1

batch_size:
  desc: null
  value: 1
annotator:
  desc: null
  value: 2
place:
  desc: null
  value: laptop
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702767722.895333
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.10.13
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
