wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702656373.83288
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      - 79
      3:
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
